name: cardbox
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  flutter_launcher_icons: ^0.9.2
  local_auth: ^1.1.8
  path_provider: ^2.0.5
  sqflite: ^2.0.0+4

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  fonts:
    - family: halter
      fonts:
        - asset: font/halter.ttf

flutter_icons:
  image_path_ios: 'assets/images/logo-ios.png'
  image_path_android: 'assets/images/logo-android.png'
  android: true
  ios: true